__include__: [
  './rtdetr_r18vd_6x_dut_anti_uav.yml',
]

output_dir: ./output/rtdetr_r18vd_200e_dut_anti_uav_mert_v2_exp1_legacy

train_dataloader:
  batch_size: 10

val_dataloader:
  num_workers: 0

MERT:
  enabled: true
  forward_mode: concat

  micro_shift:
    max_pixels: 2
    choices: [-2, -1, 0, 1, 2]
    forbid_zero_zero: true
    per_image: true
    fill_mode: baseline

  trajectory:
    enabled: true
    loss_type: smooth_l1
    weight: 0.20
    beta: 0.10
    layers: all
    xy_weight: 0.25
    wh_weight: 0.25

  schedule:
    enabled: false

  size_weight:
    enabled: true
    reference_area: 256.0
    gamma: 0.5
    max_object_area: null
    min_weight: 1.0
    max_weight: 4.0

  supervision:
    shifted_detection_loss: true

  matching:
    use_final_layer_matching: true
    exclude_dn_queries: true

  pair:
    require_fully_visible: true

  debug: false
