__include__: [
  './rtdetr_r50vd_6x_dut_anti_uav.yml',
  './include/paired_contrast_deformable_attention.yml',
]

output_dir: ./output/rtdetr_r50vd_200e_800_dut_anti_uav_paired_contrast

RTDETRTransformer:
  decoder_cross_attention:
    # R50 has 6 Decoder layers: 0, 1, 2, 3, 4, 5.
    layers:
      enabled_layers: [4, 5]
