__include__: ['./rtdetr_r18vd_dut_anti_uav.yml']

output_dir: ./output/rtdetr_r18vd_dut_anti_uav_rfaconv

RTDETR:
  backbone: PResNetWithPlugin

BackbonePlugin:
  enabled: true
  name: rfaconv
  placement: uav_placement
  stages: [S3, S4]
  conv: conv2
  params: {kernel_size: 3}
